FROM python:3.12-slim

WORKDIR /app

COPY server_api/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY server_api/ .

EXPOSE 8000

ENV PYTHONUNBUFFERED=1

CMD ["fastapi", "dev", "main.py"]