name: fastapi_app_env
channels:
  - conda-forge
  - defaults

dependencies:
  # Core dependencies managed by conda
  - python=3.10.18
  - pip=25.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - libabseil=20250127.0
  - libffi=3.4.4
  - libiconv=1.18
  - libprotobuf=5.29.3
  - libtorch=2.5.1        # Note: libtorch package, check if you need it alongside pip torch
  - libuv=1.48.0
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy       # Only numpy-base here; full numpy installed via pip below to avoid conda/pip clash
  - openssl=3.0.16
  - opentelemetry-api=1.30.0
  - setuptools=78.1.1
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2  # Keep this to satisfy conda deps; pip can have minor updates
  - vim=9.1.1397
  - wheel=0.45.1
  - wrapt=1.17.0
  - xz=5.6.4
  - zlib=1.2.13

  # Use pip to install everything else, including torch and related
  - pip:
      - accelerate==1.7.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - git+https://github.com/huggingface/diffusers.git #install cutting edge version of diffusers to try Flux Context
      - dnspython==2.7.0
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.4
      - filelock==3.18.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.32.4
      - idna==3.10
      # - importlib-metadata==8.7.0 # causes overlap/overwritten problem
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - narwhals==1.48.1
      # - numpy==2.2.6                # Installed via pip (not conda) causes overlap/overwritten rpoblem
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.2.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - rich-toolkit==0.14.8
      - rignore==0.6.2
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.47.1
      # - streamlit==1.47.0 # why was streamlit even here
      - tenacity==9.1.2
      - tokenizers==0.21.1
      - toml==0.10.2
      - torch==2.7.1               # PyTorch installed via pip 
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - typer==0.16.0
      # - typing-extensions==4.14.0 # overlap I think
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.35.0
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - zipp==3.23.0
